# Generated by Django 5.0.1 on 2024-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_table_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
