# Generated by Django 5.0.1 on 2024-01-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_table_description_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Cancelled'), ('D', 'Done'), ('I', 'IN progress')], default='I'),
        ),
    ]
